"""
Markdown report generator.

Generates reports in Markdown format suitable for documentation,
GitHub comments, and wiki pages.
"""

from typing import List

from coderefactor_pilot.reporter.base import BaseReporter
from coderefactor_pilot.rules.base import AnalysisResult, Issue, Severity


class MarkdownReporter(BaseReporter):
    """Generates reports in Markdown format.

    Produces clean Markdown output suitable for GitHub pull request
    comments, wiki pages, and documentation.

    Attributes:
        name: Format identifier.
        extension: Default file extension.
    """

    name = "markdown"
    extension = ".md"

    # Severity to emoji mapping
    SEVERITY_ICONS = {
        Severity.LOW: ":information_source:",
        Severity.MEDIUM: ":warning:",
        Severity.HIGH: ":exclamation:",
        Severity.CRITICAL: ":rotating_light:",
    }

    def generate(self, result: AnalysisResult) -> str:
        """Generate a Markdown report from analysis results.

        Args:
            result: Analysis results to report.

        Returns:
            Markdown-formatted report string.
        """
        parts = [
            self._generate_header(result),
            self._generate_summary(result),
            self._generate_issues(result),
            self._generate_footer(),
        ]
        return "\n".join(parts)

    def _generate_header(self, result: AnalysisResult) -> str:
        """Generate the report header.

        Args:
            result: Analysis results.

        Returns:
            Markdown header section.
        """
        return "# CodeRefactor Pilot - Code Review Report\n"

    def _generate_summary(self, result: AnalysisResult) -> str:
        """Generate the summary section.

        Args:
            result: Analysis results.

        Returns:
            Markdown summary section.
        """
        sev_summary = result.severity_summary()

        parts = [
            "## Summary\n",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Files Scanned | {result.files_scanned} |",
            f"| Files with Issues | {result.files_with_issues} |",
            f"| Total Issues | {len(result.issues)} |",
            f"| Scan Time | {result.scan_time:.3f}s |",
            "",
            "## Severity Breakdown\n",
            "| Severity | Count |",
            "|----------|-------|",
        ]

        for sev in Severity:
            count = sev_summary.get(sev.value, 0)
            icon = self.SEVERITY_ICONS.get(sev, "")
            parts.append(f"| {icon} {sev.value.capitalize()} | {count} |")

        parts.append("")

        # Category breakdown
        cat_summary = result.category_summary()
        if cat_summary:
            parts.append("## Category Breakdown\n")
            parts.append("| Category | Count |")
            parts.append("|----------|-------|")
            for category, count in sorted(cat_summary.items(), key=lambda x: -x[1]):
                parts.append(f"| {category.capitalize()} | {count} |")
            parts.append("")

        return "\n".join(parts)

    def _generate_issues(self, result: AnalysisResult) -> str:
        """Generate the issues section.

        Args:
            result: Analysis results.

        Returns:
            Markdown issues section.
        """
        if not result.issues:
            return "## Issues\n\nNo issues found! Code looks clean.\n"

        parts = [f"## Issues ({len(result.issues)})\n"]

        # Group issues by file
        by_file: dict = {}
        for issue in result.issues:
            if issue.file_path not in by_file:
                by_file[issue.file_path] = []
            by_file[issue.file_path].append(issue)

        for file_path, issues in sorted(by_file.items()):
            parts.append(f"### `{file_path}`\n")

            for issue in issues:
                icon = self.SEVERITY_ICONS.get(issue.severity, "")
                parts.append(
                    f"- **{icon} [{issue.severity.value.upper()}] {issue.rule_name}** "
                    f"(`{issue.rule_id}`) - Line {issue.line}"
                )
                parts.append(f"  - {issue.message}")

                if issue.code_snippet:
                    parts.append(f"  ```")
                    parts.append(f"  {issue.code_snippet}")
                    parts.append(f"  ```")

                if issue.suggestion:
                    parts.append(f"  - **Suggestion:** {issue.suggestion}")

                parts.append("")

        return "\n".join(parts)

    def _generate_footer(self) -> str:
        """Generate the report footer.

        Returns:
            Markdown footer section.
        """
        return "\n---\n*Generated by CodeRefactor Pilot*\n"
